#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
# config/routes.yaml
app.swagger:
    path: /doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
app.swagger_ui:
    path: /
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

